/*
 * Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 */
/*
 * Copyright (c) 2006 Sun Microsystems, Inc. All Rights Reserved.
 *
 *     Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * - Redistribution of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * - Redistribution in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *     Neither the name of Sun Microsystems, Inc. or the names of contributors
 * may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 *     This software is provided "AS IS," without a warranty of any kind. ALL
 * EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND WARRANTIES, INCLUDING
 * ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * OR NON-INFRINGEMENT, ARE HEREBY EXCLUDED. SUN MICROSYSTEMS, INC. ("SUN")
 * AND ITS LICENSORS SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE
 * AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS
 * DERIVATIVES. IN NO EVENT WILL SUN OR ITS LICENSORS BE LIABLE FOR ANY LOST
 * REVENUE, PROFIT OR DATA, OR FOR DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL,
 * INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THE THEORY
 * OF LIABILITY, ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE,
 * EVEN IF SUN HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 *     You acknowledge that this software is not designed, licensed or
 * intended for use in the design, construction, operation or maintenance of
 * any nuclear facility.
 */

#ifndef	_SCA_RC_H
#define	_SCA_RC_H

#pragma ident	"@(#)sca_rc.h	1.2	05/07/22 SMI"

#include "common.h"
#include "pkcs11types.h"

#ifdef	__cplusplus
extern "C" {
#endif

/*
 * PKCS11 defines one set of error code and the framework defines another.
 * Although the names are similar, but the actual values may be different.
 * From the framework and below, the framework error codes (prefixed by CRYPTO_)
 * are used. In the userland, the PKCS11 error codes (prefixed by CKR_)
 * are used. The following is to map the framework error codes to the
 * PKCS11 error codes. Make sure to return the PKCS11 error codes to
 * the userland.
 */

static int sca_rc[] = {
	CKR_OK,
	/* #define CRYPTO_SUCCESS			0x00000000 */
	CKR_CANCEL,
	/* #define CRYPTO_CANCEL			0x00000001 */
	CKR_HOST_MEMORY,
	/* #define CRYPTO_HOST_MEMORY			0x00000002 */
	CKR_GENERAL_ERROR,
	/* #define CRYPTO_GENERAL_ERROR			0x00000003 */
	CKR_FUNCTION_FAILED,
	/* #define CRYPTO_FAILED			0x00000004 */
	CKR_ARGUMENTS_BAD,
	/* #define CRYPTO_ARGUMENTS_BAD			0x00000005 */
	CKR_ATTRIBUTE_READ_ONLY,
	/* #define CRYPTO_ATTRIBUTE_READ_ONLY		0x00000006 */
	CKR_ATTRIBUTE_SENSITIVE,
	/* #define CRYPTO_ATTRIBUTE_SENSITIVE		0x00000007 */
	CKR_ATTRIBUTE_TYPE_INVALID,
	/* #define CRYPTO_ATTRIBUTE_TYPE_INVALID	0x00000008 */
	CKR_ATTRIBUTE_VALUE_INVALID,
	/* #defineCRYPTO_ATTRIBUTE_VALUE_INVALID	0x00000009 */
	CKR_FUNCTION_CANCELED,
	/* #define CRYPTO_CANCELED			0x0000000A */
	CKR_DATA_INVALID,
	/* #define CRYPTO_DATA_INVALID			0x0000000B */
	CKR_DATA_LEN_RANGE,
	/* #define CRYPTO_DATA_LEN_RANGE		0x0000000C */
	CKR_DEVICE_ERROR,
	/* #define CRYPTO_DEVICE_ERROR			0x0000000D */
	CKR_DEVICE_MEMORY,
	/* #define CRYPTO_DEVICE_MEMORY			0x0000000E */
	CKR_DEVICE_REMOVED,
	/* #define CRYPTO_DEVICE_REMOVED		0x0000000F */
	CKR_ENCRYPTED_DATA_INVALID,
	/* #define CRYPTO_ENCRYPTED_DATA_INVALID	0x00000010 */
	CKR_ENCRYPTED_DATA_LEN_RANGE,
	/* #define CRYPTO_ENCRYPTED_DATA_LEN_RANGE	0x00000011 */
	CKR_KEY_HANDLE_INVALID,
	/* #define CRYPTO_KEY_HANDLE_INVALID		0x00000012 */
	CKR_KEY_SIZE_RANGE,
	/* #define CRYPTO_KEY_SIZE_RANGE		0x00000013 */
	CKR_KEY_TYPE_INCONSISTENT,
	/* #define CRYPTO_KEY_TYPE_INCONSISTENT		0x00000014 */
	CKR_KEY_NOT_NEEDED,
	/* #define CRYPTO_KEY_NOT_NEEDED		0x00000015 */
	CKR_KEY_CHANGED,
	/* #define CRYPTO_KEY_CHANGED			0x00000016 */
	CKR_KEY_NEEDED,
	/* #define CRYPTO_KEY_NEEDED			0x00000017 */
	CKR_KEY_INDIGESTIBLE,
	/* #define CRYPTO_KEY_INDIGESTIBLE		0x00000018 */
	CKR_KEY_FUNCTION_NOT_PERMITTED,
	/* #define CRYPTO_KEY_FUNCTION_NOT_PERMITTED	0x00000019 */
	CKR_KEY_NOT_WRAPPABLE,
	/* #define CRYPTO_KEY_NOT_WRAPPABLE		0x0000001A */
	CKR_KEY_UNEXTRACTABLE,
	/* #define CRYPTO_KEY_UNEXTRACTABLE		0x0000001B */
	CKR_MECHANISM_INVALID,
	/* #define CRYPTO_MECHANISM_INVALID		0x0000001C */
	CKR_MECHANISM_PARAM_INVALID,
	/* #define CRYPTO_MECHANISM_PARAM_INVALID	0x0000001D */
	CKR_OBJECT_HANDLE_INVALID,
	/* #define CRYPTO_OBJECT_HANDLE_INVALID		0x0000001E */
	CKR_OPERATION_ACTIVE,
	/* #define CRYPTO_OPERATION_IS_ACTIVE		0x0000001F */
	CKR_OPERATION_NOT_INITIALIZED,
	/* #define CRYPTO_OPERATION_NOT_INITIALIZED	0x00000020 */
	CKR_PIN_INCORRECT,
	/* #define CRYPTO_PIN_INCORRECT			0x00000021 */
	CKR_PIN_INVALID,
	/* #define CRYPTO_PIN_INVALID			0x00000022 */
	CKR_PIN_LEN_RANGE,
	/* #define CRYPTO_PIN_LEN_RANGE			0x00000023 */
	CKR_PIN_EXPIRED,
	/* #define CRYPTO_PIN_EXPIRED			0x00000024 */
	CKR_PIN_LOCKED,
	/* #define CRYPTO_PIN_LOCKED			0x00000025 */
	CKR_SESSION_CLOSED,
	/* #define CRYPTO_SESSION_CLOSED		0x00000026 */
	CKR_SESSION_COUNT,
	/* #define CRYPTO_SESSION_COUNT			0x00000027 */
	CKR_SESSION_HANDLE_INVALID,
	/* #define CRYPTO_SESSION_HANDLE_INVALID	0x00000028 */
	CKR_SESSION_READ_ONLY,
	/* #define CRYPTO_SESSION_READ_ONLY		0x00000029 */
	CKR_SESSION_EXISTS,
	/* #define CRYPTO_SESSION_EXISTS		0x0000002A */
	CKR_SESSION_READ_ONLY_EXISTS,
	/* #define CRYPTO_SESSION_READ_ONLY_EXISTS	0x0000002B */
	CKR_SESSION_READ_WRITE_SO_EXISTS,
	/* #define CRYPTO_SESSION_READ_WRITE_SO_EXISTS	0x0000002C */
	CKR_SIGNATURE_INVALID,
	/* #define CRYPTO_SIGNATURE_INVALID		0x0000002D */
	CKR_SIGNATURE_LEN_RANGE,
	/* #define CRYPTO_SIGNATURE_LEN_RANGE		0x0000002E */
	CKR_TEMPLATE_INCOMPLETE,
	/* #define CRYPTO_TEMPLATE_INCOMPLETE		0x0000002F */
	CKR_TEMPLATE_INCONSISTENT,
	/* #define CRYPTO_TEMPLATE_INCONSISTENT		0x00000030 */
	CKR_UNWRAPPING_KEY_HANDLE_INVALID,
	/* #define CRYPTO_UNWRAPPING_KEY_HANDLE_INVALID	0x00000031 */
	CKR_UNWRAPPING_KEY_SIZE_RANGE,
	/* #define CRYPTO_UNWRAPPING_KEY_SIZE_RANGE	0x00000032 */
	CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT,
	/* #define CRYPTO_UNWRAPPING_KEY_TYPE_INCONSISTENT 0x00000033 */
	CKR_USER_ALREADY_LOGGED_IN,
	/* #define CRYPTO_USER_ALREADY_LOGGED_IN	0x00000034 */
	CKR_USER_NOT_LOGGED_IN,
	/* #define CRYPTO_USER_NOT_LOGGED_IN		0x00000035 */
	CKR_USER_PIN_NOT_INITIALIZED,
	/* #define CRYPTO_USER_PIN_NOT_INITIALIZED	0x00000036 */
	CKR_USER_TYPE_INVALID,
	/* #define CRYPTO_USER_TYPE_INVALID		0x00000037 */
	CKR_USER_ANOTHER_ALREADY_LOGGED_IN,
	/* #define CRYPTO_USER_ANOTHER_ALREADY_LOGGED_IN 0x00000038 */
	CKR_USER_TOO_MANY_TYPES,
	/* #define CRYPTO_USER_TOO_MANY_TYPES		0x00000039 */
	CKR_WRAPPED_KEY_INVALID,
	/* #define CRYPTO_WRAPPED_KEY_INVALID		0x0000003A */
	CKR_WRAPPED_KEY_LEN_RANGE,
	/* #define CRYPTO_WRAPPED_KEY_LEN_RANGE		0x0000003B */
	CKR_WRAPPING_KEY_HANDLE_INVALID,
	/* #define CRYPTO_WRAPPING_KEY_HANDLE_INVALID	0x0000003C */
	CKR_WRAPPING_KEY_SIZE_RANGE,
	/* #define CRYPTO_WRAPPING_KEY_SIZE_RANGE	0x0000003D */
	CKR_WRAPPING_KEY_TYPE_INCONSISTENT,
	/* #define CRYPTO_WRAPPING_KEY_TYPE_INCONSISTENT 0x0000003E */
	CKR_RANDOM_SEED_NOT_SUPPORTED,
	/* #define CRYPTO_RANDOM_SEED_NOT_SUPPORTED	0x0000003F */
	CKR_RANDOM_NO_RNG,
	/* #define CRYPTO_RANDOM_NO_RNG			0x00000040 */
	CKR_DOMAIN_PARAMS_INVALID,
	/* #define CRYPTO_DOMAIN_PARAMS_INVALID		0x00000041 */
	CKR_BUFFER_TOO_SMALL,
	/* #define CRYPTO_BUFFER_TOO_SMALL		0x00000042 */
	CKR_INFORMATION_SENSITIVE,
	/* #define CRYPTO_INFORMATION_SENSITIVE		0x00000043 */
	CKR_FUNCTION_NOT_SUPPORTED,
	/* #define CRYPTO_NOT_SUPPORTED			0x00000044 */

	/*
	 * For the framework error codes that are not used or there are
	 * no corresponding ones in PKCS11 error codes, define them
	 * CKR_GENERAL_ERROR
	 */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_QUEUED			0x00000045 */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_BUFFER_TOO_BIG		0x00000046 */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_INVALID_CONTEXT		0x00000047 */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_INVALID_MAC		0x00000048 */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_MECH_NOT_SUPPORTED	0x00000049 */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_INCONSISTENT_ATTRIBUTE	0x0000004A */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_NO_PERMISSION		0x0000004B */
	CKR_SLOT_ID_INVALID,
	/* #define	CRYPTO_INVALID_PROVIDER_ID	0x0000004C */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_VERSION_MISMATCH		0x0000004D */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_BUSY			0x0000004E */
	CKR_SLOT_ID_INVALID,
	/* #define	CRYPTO_UNKNOWN_PROVIDER		0x0000004F */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_MODVERIFICATION_FAILED	0x00000050 */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_OLD_CTX_TEMPLATE		0x00000051 */
	CKR_GENERAL_ERROR,
	/* #define	CRYPTO_WEAK_KEY			0x00000052 */
};

#ifdef	__cplusplus
}
#endif

#endif	/* _SCA_RC_H */
